name: XMake

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: clang-format Check
      run: clang-format --dry-run --Werror src/*.c* src/*.h*

    - name: Configure XMake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
        actions-cache-folder: '.xmake-cache'

    - name: cache xmake
      uses: actions/cache@v2
      with:
        path: |
          ${{github.workspace}}/build/.build_cache
          .xmake-cache
        key: ${{ runner.os }}-xmake-${{ hashFiles('**/xmake.lua') }}

    - name: Build
      run: xmake -y
